// vue-app/src/components/AboutSection.tsx
import { useI18n } from '@/i18n'

// 交叉研究方向：每行一个方向，由多个关键词组成（术语为领域标准英文，中英文通用）
const researchDirections: string[][] = [
  ['3D Gaussian Splatting', '3D scene reconstruction'],
  ['sparse vision transformers', 'sparse attention', 'multimodal representation learning'],
]

export default function AboutSection() {
  const { t } = useI18n()

  return (
    <section className="section" id="about">
      <div className="section-inner reveal">
        <div className="section-head">
          <h2 className="section-title">{t('about.title')}</h2>
        </div>

        <div className="about-info stagger">
          <div className="info-item info-item--research">
            <span className="info-label">{t('about.label.research')}</span>
            <div className="info-value">
              {researchDirections.map((dir, i) => (
                <div className="research-direction" key={i}>
                  <span className="dir-index">{String(i + 1).padStart(2, '0')}</span>
                  {dir.map((kw, j) => (
                    <span className="chip" key={j}>
                      {kw}
                    </span>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

// vue-app/src/components/AboutSection.vue
<template>
  <section class="section" id="about">
    <div class="section-inner reveal">
      <div class="section-head">
        <h2 class="section-title">{{ t('about.title') }}</h2>
      </div>

      <div class="about-info stagger">
        <div class="info-item info-item--research">
          <span class="info-label">{{ t('about.label.research') }}</span>
          <span class="info-value">
            <div class="research-direction" v-for="(dir, i) in researchDirections" :key="i">
              <span class="dir-index">{{ String(i + 1).padStart(2, '0') }}</span>
              <span class="chip" v-for="(kw, j) in dir" :key="j">{{ kw }}</span>
            </div>
          </span>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { useI18nStore } from '@/stores/i18n'
const { t } = useI18nStore()

// 交叉研究方向：每行一个方向，由多个关键词组成（术语为领域标准英文，中英文通用）
const researchDirections: string[][] = [
  ['3D Gaussian Splatting', '3D scene reconstruction'],
  ['sparse vision transformers', 'sparse attention', 'multimodal representation learning'],
]
</script>
