// react-app/src/components/BackTopButton.tsx
import IconChevronUp from '@/components/IconChevronUp'

export default function BackTopButton({ show }: { show: boolean }) {
  function scrollToTop() {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  return (
    <button
      className={`back-top-btn ${show ? 'show' : ''}`}
      onClick={scrollToTop}
      aria-label="回到顶部"
    >
      <IconChevronUp />
    </button>
  )
}

// vue-app/src/components/BackTopButton.vue
<template>
  <button class="back-top-btn" :class="{ show }" @click="scrollToTop" aria-label="回到顶部">
    <IconChevronUp />
  </button>
</template>

<script setup lang="ts">
import IconChevronUp from '@/components/icons/IconChevronUp.vue'

defineProps<{ show: boolean }>()

function scrollToTop() {
  window.scrollTo({ top: 0, behavior: 'smooth' })
}
</script>
