// react-app/src/components/FooterSection.tsx
import { useI18n } from '@/i18n'

export default function FooterSection() {
  const { t } = useI18n()

  return (
    <footer className="footer">
      <div className="footer-inner">
        <span className="sig">
          <b>LiYaze</b> — Profile &amp; Selected Work
        </span>
        <span dangerouslySetInnerHTML={{ __html: t('footer.copyright') }} />
      </div>
    </footer>
  )
}

// vue-app/src/components/FooterSection.vue
<template>
  <footer class="footer">
    <div class="footer-inner">
      <span class="sig"><b>LiYaze</b> — Profile & Selected Work</span>
      <span v-html="t('footer.copyright')"></span>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { useI18nStore } from '@/stores/i18n'
const { t } = useI18nStore()
</script>
