// vue-app/src/components/LangToggle.vue
<template>
  <div class="nav-actions-pill" id="langPill">
    <button class="lang-toggle" @click="toggleLocale" :aria-label="t('lang.toggleAria')">
      <span :key="locale" class="lang-icon toggle-pop">{{ t('lang.toggle') }}</span>
    </button>
    <button class="theme-toggle" @click="toggleTheme" :aria-label="t('theme.toggleAria')">
      <span :key="theme" class="theme-icon toggle-pop">{{ theme === 'light' ? '☾' : '☀' }}</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useI18nStore } from '@/stores/i18n'
const i18nStore = useI18nStore()
const { t, toggleLocale, toggleTheme } = i18nStore
const { locale, theme } = storeToRefs(i18nStore)
</script>

// vue-app/src/components/LangToggle.tsx
import { useI18n } from '@/i18n'

export default function LangToggle() {
  const { t, toggleLocale, toggleTheme, locale, theme } = useI18n()

  return (
    <div className="nav-actions-pill" id="langPill">
      <button className="lang-toggle" onClick={toggleLocale} aria-label={t('lang.toggleAria')}>
        <span key={locale} className="lang-icon toggle-pop">
          {t('lang.toggle')}
        </span>
      </button>
      <button className="theme-toggle" onClick={toggleTheme} aria-label={t('theme.toggleAria')}>
        <span key={theme} className="theme-icon toggle-pop">
          {theme === 'light' ? '☾' : '☀'}
        </span>
      </button>
    </div>
  )
}
