// react-app/src/App.tsx
import LangToggle from '@/components/LangToggle'
import { Routes, Route } from 'react-router-dom'
import HomeView from '@/views/HomeView'

export default function App() {
  return (
    <>
      <div className="bg-aura" aria-hidden="true" />
      <LangToggle />
      <Routes>
        <Route path="/" element={<HomeView />} />
      </Routes>
    </>
  )
}

// vue-app/src/App.vue
<template>
  <div class="bg-aura" aria-hidden="true"></div>
  <LangToggle />
  <router-view />
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useI18nStore } from '@/stores/i18n'
import LangToggle from '@/components/LangToggle.vue'

const { setLocale, locale, applyTheme } = useI18nStore()

onMounted(() => {
  setLocale(locale)
  applyTheme()
})
</script>
